# example netlify.toml
[build]
command = "npm run build"
functions = "netlify/functions"
publish = "dist"

## Uncomment to use this redirect for Single Page Applications like create-react-app.
## Not needed for static site generators.
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[dev]
command = "npm run dev" # Command to start your dev server
port = 8000             # Port that the dev server will be listening on
publish = "dist"        # Folder with the static content for _redirect file
framework = "vite"      # Framework used for the project
targetPort = 5173       # Port that the dev server will be listening on
autoLaunch = false      # Prevent auto-opening browser
